CREATE TABLE ALLERGEN
(
	AllergenID  SERIAL NOT NULL ,
	AllergenName  varchar(20)  NULL 
);

/*
CREATE  UNIQUE INDEX XPKALLERGEN ON ALLERGEN
(
	AllergenID  ASC
);
*/

ALTER TABLE ALLERGEN
	ADD CONSTRAINT  XPKALLERGEN PRIMARY KEY (AllergenID);


CREATE TABLE FOOD
(
	BarcodeNo  varchar(20)  NOT NULL ,
	FoodName  varchar(20)  NULL ,
	Brand  varchar(20)  NULL ,
	WeightVolume  varchar(10)  NULL ,
	Ingredients  varchar(2000)  NULL 
);

/*
CREATE  UNIQUE INDEX XPKFOOD ON FOOD
(
	BarcodeNo  ASC
);
*/

ALTER TABLE FOOD
	ADD CONSTRAINT  XPKFOOD PRIMARY KEY (BarcodeNo);


CREATE TABLE FOOD_CONTAINS
(
	BarcodeNo  varchar(20) NOT NULL ,
	AllergenID  INTEGER NOT NULL 
);


CREATE TABLE NUTRITION
(
	Fat  INTEGER  NULL ,
	Protein  INTEGER  NULL ,
	Carbs  INTEGER  NULL ,
	Calorie  INTEGER  NULL ,
	BarcodeNo  varchar(20)  NOT NULL 
);

/*
CREATE  UNIQUE INDEX XPKNUTRITION ON NUTRITION
(
	BarcodeNo  ASC
);
*/

ALTER TABLE NUTRITION
	ADD CONSTRAINT  XPKNUTRITION PRIMARY KEY (BarcodeNo);


CREATE TABLE PERSON
(
	UserID  SERIAL NOT NULL ,
	E_Mail  varchar(20)  NOT NULL,
	PersonName  varchar(20)  NULL ,
	PersonSurname  varchar(20)  NULL ,
	TelephoneNo  varchar(20)  NULL ,
	SaltedPassword  varchar(20)  NOT NULL ,
	Height  INTEGER  NULL ,
	Weight  INTEGER  NULL ,
	is_admin  BOOLEAN  NOT NULL
);

/*
CREATE  UNIQUE INDEX XPKPERSON ON PERSON
(
	UserID  ASC
);
*/

ALTER TABLE PERSON
	ADD CONSTRAINT  XPKPERSON PRIMARY KEY (UserID);


CREATE TABLE PERSONHASALLERGEN
(
	AllergenID  SERIAL NOT NULL ,
	UserID  INTEGER NOT NULL 
);


ALTER TABLE FOOD_CONTAINS
	ADD CONSTRAINT  R_1 FOREIGN KEY (BarcodeNo) REFERENCES FOOD(BarcodeNo) ON DELETE SET NULL;


ALTER TABLE FOOD_CONTAINS
	ADD CONSTRAINT  R_2 FOREIGN KEY (AllergenID) REFERENCES ALLERGEN(AllergenID) ON DELETE SET NULL;


ALTER TABLE NUTRITION
	ADD CONSTRAINT  R_5 FOREIGN KEY (BarcodeNo) REFERENCES FOOD(BarcodeNo);


ALTER TABLE PERSONHASALLERGEN
	ADD CONSTRAINT  R_3 FOREIGN KEY (AllergenID) REFERENCES ALLERGEN(AllergenID) ON DELETE SET NULL;


ALTER TABLE PERSONHASALLERGEN
	ADD CONSTRAINT  R_4 FOREIGN KEY (UserID) REFERENCES PERSON(UserID) ON DELETE SET NULL;
